// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/track-booking.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
var track_booking_default = defineTool({
  name: "track_booking",
  title: "Track booking",
  description: "Look up a booking's status, schedule, and assigned provider by booking number.",
  inputSchema: {
    booking_number: z.string().min(3).describe("The public booking number (e.g. MFN-000123).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ booking_number }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("bookings").select("booking_number, status, scheduled_at, city, payment_status, payment_method, assigned_provider_id").eq("booking_number", booking_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Booking not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List medical services",
  description: "List active medical home-care services offered on the platform, with optional category filter.",
  inputSchema: {
    category: z2.string().optional().describe("Optional category slug or name to filter by."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("services").select("id, name_ar, name_en, category, price, price_type, is_active").eq("is_active", true).limit(limit ?? 50);
    if (category) q = q.or(`category.eq.${category},category_ar.eq.${category},category_en.eq.${category}`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { services: data }
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
var list_vendors_default = defineTool3({
  name: "list_marketplace_vendors",
  title: "List marketplace vendors",
  description: "List approved medical marketplace vendors (pharmacies, medical stores, etc.), filterable by type or city.",
  inputSchema: {
    vendor_type: z3.string().optional().describe("e.g. pharmacy, medical_store, optics."),
    city: z3.string().optional().describe("Filter by city."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vendor_type, city, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("marketplace_vendors_public").select("id, store_name, vendor_type, city, rating, logo_url, business_phone, business_whatsapp").limit(limit ?? 50);
    if (vendor_type) q = q.eq("vendor_type", vendor_type);
    if (city) q = q.ilike("city", `%${city}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vendors: data }
    };
  }
});

// src/lib/mcp/index.ts
var SUPABASE_URL = "https://pasfkwniarukkdfdclah.supabase.co";
var mcp_default = defineMcp({
  name: "mfn-mcp",
  title: "MFN \u2014 Medical Field Nation",
  version: "0.1.0",
  instructions: "Authenticated read-only tools for the MFN medical home-care platform. Use `track_booking` to check a booking's status by number, `list_services` to browse offered home-care services, and `list_marketplace_vendors` to browse pharmacies and medical stores in the Medical Marketplace.",
  // Require a valid Supabase-issued OAuth access token on every MCP call so the
  // server is not open to anonymous callers once published.
  auth: auth.oauth.issuer({
    issuer: `${SUPABASE_URL}/auth/v1`,
    acceptedAudiences: "authenticated",
    resourceName: "MFN MCP"
  }),
  tools: [track_booking_default, list_services_default, list_vendors_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
